spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mydatabase

app:
  smtp:
    host: smtp.elasticemail.com
    port: 2525
    username: joao.fodra.veloso@gmail.com
    password: C9D9E981BDEF932EB695083ADBB8A029B41E
